//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace NX_lims_Softlines_Command_System.Models
{
    using NX_lims_Softlines_Command_System.Domain.Model.Interface;
    using System;
    using System.Collections.Generic;
    
    public partial class WetParameters:IWetParam
    {
        [Key]
        public long ID { get; set; }
        public string StandardType { get; set; }
        public string Program { get; set; }
        public string Temperature { get; set; }
        public Nullable<int> SteelBall { get; set; }
        public string WashingProcedure { get; set; }
        public string DryCondition { get; set; }
        public string DryProcedure { get; set; }
        public string SCI { get; set; }
        public string IsSensitive { get; set; }
        public string Ballast { get; set; }
        public string OrderNumber { get; set; }
        public string Item { get; set; }
        public Nullable<int> AfterWash { get; set; }
        public string Cycle { get; set; }
    }
}
